name: auto deploy

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'  # 设置你希望使用的 Python 版本，建议使用稳定版本

      - name: Create user_info.json from environment variable
        run: echo "$USER_INFO" > user_info.json
        env:
          user_info.json: ${{ secrets.USER_INFO}}  # 从GitHub Secrets中获取环境变量

      - name: Create account.json from environment variable
        run: echo "$ACCOUNT" > account.json
        env:
          account.json: ${{ secrets.ACCOUNT}}  # 从GitHub variables中获取环境变量

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行登录脚本
        env:
          user_info.json: ${{ secrets.USER_INFO }}
          account.json: ${{ secrets.ACCOUNT }}

        run: |
          python login_auto_deploy.py