name: manual start

on:
  workflow_dispatch:
    inputs:
      start_type:
        description: '请选择启动方式'
        required: true
        default: 'restart'
        type: choice
        options:
          - restart
          - reset
          - keepalive
      interval:
        description: '请选择保活间隔时间(分钟)'
        required: true
        default: '20'
        type: choice
        options:
        - 20
        - 30
        - 40
        - 50
        - 60
        
jobs:
  job-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "start_type: $START_TYPE"
          echo "INTERVAL: $INTERVAL"
          echo "ENV_CMD: py $START_TYPE $INTERVAL"
        env:
          INTERVAL: ${{ inputs.interval }}
          START_TYPE: ${{ inputs.start_type }}
